### ISSUE TITLE
Planned release

### ISSUE THREAD

**Issue by boddissattva** [fridujo/glacio#85]
Is a release planned yet ?
We plan at [chutney](https://github.com/chutney-testing) to soon merge a branch using your parser and therfore would like a release if it's possible.

**Comment by ledoyen** [comment]
@boddissattva release 0.0.1 is done it should take around 2 hours to get to Maven Central.

Cheers :tada:

**Comment by ledoyen** [comment]
https://search.maven.org/artifact/com.github.fridujo/glacio/0.0.1/pom
